apiVersion: v2
name: decentralized-iam
description: Umbrella Chart for the FIWARE decentralized-iam, combining FIWARE vc-authentication and odrl-authorization components.
type: application
version: 0.3.0
dependencies:
  - name: vc-authentication
    repository: https://fiware.github.io/vc-authentication/
    version: 0.2.1
  - name: odrl-authorization
    repository: https://fiware.github.io/odrl-authorization/
    version: 1.0.5