apiVersion: v2
name: decentralized-iam
description: Umbrella Chart for the FIWARE decentralized-iam, combining FIWARE vc-authentication and odrl-authorization components.
type: application
version: 0.2.1
dependencies:
  - name: vc-authentication
    alias: vcAuthentication
    repository: https://fiware.github.io/vc-authentication/
    version: 1.0.0
  - name: odrl-authorization
    alias: odrlAuthorization
    repository: https://fiware.github.io/odrl-authorization/
    version: 1.0.5
